name: download-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
    contents: write
    
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest] #, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
    # https://netstorage.allwinnertech.com:5001/sharing/F8oAGoG9h
      - shell: bash
        run: |
          curl 'https://netstorage.allwinnertech.com:5001/fsdownload/F8oAGoG9h/V853%20NPU%20Toolkits.zip' \
            -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
            -H 'accept-language: zh-TW,zh;q=0.9' \
            -H 'cache-control: no-cache' \
            -b 'sharing_sid=2nSw3mnUzLBPF2bBPT51CmdFIvJBsSdy' \
            -H 'pragma: no-cache' \
            -H 'priority: u=0, i' \
            -H 'referer: https://netstorage.allwinnertech.com:5001/sharing/F8oAGoG9h' \
            -H 'sec-ch-ua: "Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"' \
            -H 'sec-ch-ua-mobile: ?0' \
            -H 'sec-ch-ua-platform: "Windows"' \
            -H 'sec-fetch-dest: document' \
            -H 'sec-fetch-mode: navigate' \
            -H 'sec-fetch-site: same-origin' \
            -H 'sec-fetch-user: ?1' \
            -H 'upgrade-insecure-requests: 1' \
            -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36' \
            --output download.zip && \
          7z x download.zip -o"downloads" && \
          ls
      
      # - name: Archive Release
      #   uses: thedoctor0/zip-release@master
      #   with:
      #     type: 'zip'
      #     path: ${{ github.event.repository.name }}*
      #     filename: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "downloads/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
